# Generated by Django 2.2.11 on 2020-04-26 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=200)),
                ('query_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_result', models.CharField(max_length=200)),
                ('prediction_score', models.IntegerField()),
                ('related_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine_learning.Query')),
            ],
        ),
    ]
