# Generated by Django 2.2.11 on 2020-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='prediction_score',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
