# Generated by Django 2.2.11 on 2020-05-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_auto_20200430_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10),
        ),
    ]
