# Generated by Django 2.2.11 on 2020-05-01 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_auto_20200501_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_class',
            field=models.IntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')], validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
