# Generated by Django 2.2.11 on 2020-05-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0006_auto_20200501_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_fare',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
