# Generated by Django 2.2.11 on 2020-05-01 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0007_auto_20200502_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_age',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_fare',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
