# Generated by Django 2.2.11 on 2020-05-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0008_auto_20200502_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicprediction',
            name='prediction_probability',
            field=models.DecimalField(decimal_places=8, max_digits=9),
        ),
    ]
