# Generated by Django 2.2.11 on 2020-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0009_auto_20200502_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titanicprediction',
            old_name='prediction_probability',
            new_name='prediction_probability_0',
        ),
        migrations.AddField(
            model_name='titanicprediction',
            name='prediction_probability_1',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
