# Generated by Django 2.2.11 on 2020-05-03 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0010_auto_20200502_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titanicquery',
            options={'verbose_name_plural': 'TitanicQueries'},
        ),
        migrations.AlterField(
            model_name='titanicprediction',
            name='prediction_probability_0',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='titanicprediction',
            name='prediction_probability_1',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_age',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_fare',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
