# Generated by Django 2.2.11 on 2020-05-03 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0011_auto_20200503_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titanicprediction',
            options={'verbose_name_plural': 'Titanic Predictions'},
        ),
        migrations.AlterModelOptions(
            name='titanicquery',
            options={'verbose_name_plural': 'Titanic Queries'},
        ),
        migrations.AddField(
            model_name='titanicprediction',
            name='prediction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
