# Generated by Django 2.2.11 on 2020-05-05 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0013_auto_20200505_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicquery',
            name='passenger_fare',
            field=models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
