# Generated by Django 2.2.11 on 2020-05-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0014_auto_20200505_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='titanicquery',
            name='user',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
