# Generated by Django 2.2.11 on 2020-05-14 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0017_textprocessing_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textprocessing',
            options={'verbose_name_plural': 'Text Processing'},
        ),
        migrations.AddField(
            model_name='textprocessing',
            name='processing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
