# Generated by Django 2.2.11 on 2020-05-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0020_auto_20200514_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textprocessing',
            name='text_area',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='textprocessingresult',
            name='text_result',
            field=models.CharField(max_length=1000),
        ),
    ]
