# Generated by Django 2.2.11 on 2020-05-16 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0023_auto_20200516_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='textprocessing',
            name='language_choice',
            field=models.CharField(choices=[('turkish', 'TR'), ('english', 'ENG')], default='TR', max_length=10),
        ),
        migrations.AlterField(
            model_name='textprocessing',
            name='text_area',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
