# Generated by Django 2.2.11 on 2020-05-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0026_auto_20200524_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telcochurnprediction',
            name='prediction_result',
        ),
        migrations.RemoveField(
            model_name='telcochurnprediction',
            name='prediction_result_proba_0',
        ),
        migrations.RemoveField(
            model_name='telcochurnprediction',
            name='prediction_result_proba_1',
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_ada',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_knn',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_proba_ada',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_proba_knn',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_proba_rand',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_proba_svc',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=5),
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_rand',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='telcochurnprediction',
            name='result_svc',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
