# Generated by Django 2.2.11 on 2020-05-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0027_auto_20200524_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telcochurnprediction',
            name='result_ada',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='telcochurnprediction',
            name='result_knn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='telcochurnprediction',
            name='result_rand',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='telcochurnprediction',
            name='result_svc',
            field=models.CharField(max_length=10),
        ),
    ]
